### ISSUE TITLE
if there is only 1 row still table taking some fix height

### ISSUE THREAD

**Issue by piyushSinghalDemo** [richardtallent/vue-scrolling-table#13]
In my grid if there is only row at that time it is showing some dead area, is there any way i can provide only max-height, not fixed height. For example
getting actual output--->
![grid](https://user-images.githubusercontent.com/30336741/55461862-22386780-5613-11e9-8c1e-b1da4f6f1598.png)

However if there is not too much record expected output---
![grid1](https://user-images.githubusercontent.com/30336741/55461986-6a578a00-5613-11e9-8b25-261769705a40.png)

**Comment by richardtallent** [comment]
This component is designed to have its height be provide by its parent element, so it will take whatever you give it. Setting a height automatically would be pretty difficult, especially with some of the details of how CSS metrics work with table elements.

You could, however, add your own code to the parent wrapper element to set a max height based on the number of visible elements in the table. For example, something like this (depending how tall your actual rows are):

```HTML
<div :style="'max-height: calc(16pt * ' + (rows.length + 1) + ')'">
  <vue-scrolling-table>...<tr v-for="row in rows".../>...</vue-scrolling-table>
</div>
```

**Comment by piyushSinghalDemo** [comment]
this idea worked thanx
