### ISSUE TITLE
property deadAreaColor working fine in google crome, but in firefox 66.0.3 (64-bit) not reflecting, it is taking default color.

### ISSUE THREAD

**Issue by piyushSinghalDemo** [richardtallent/vue-scrolling-table#16]
property deadAreaColor working fine in google crome, but in firefox 66.0.3 (64-bit) not reflecting, it is taking default color.

**Comment by piyushSinghalDemo** [comment]
property deadAreaColor working fine in google crome, but in firefox 66.0.3 (64-bit) not reflecting, it is taking default color.

**Comment by richardtallent** [comment]
Can you check using the live online sample version?

https://www.tallent.us/vue-scrolling-table/

I just tested with Firefox 66.0.3 (Mac, 64-bit) and can't reproduce the issue -- I can choose a dead area color using the provided color input and it shows correctly (you must first change the number of records from 100 to something much smaller for there to _be_ a dead area to see, of course).

**Comment by piyushSinghalDemo** [comment]
hi Richard, 
I don't know why but i am get the same issue in online sample version "https://www.tallent.us/vue-scrolling-table"

![scroll-issue](https://user-images.githubusercontent.com/30336741/57080653-964c5500-6d10-11e9-9e6d-ae5fe065f6ad.png)

however it is working fine in google chrome

**Comment by richardtallent** [comment]
In the screen shot you posted, there is no "dead area," so the dead area color is not showing. The "dead area" is the area of the table component *not* used by the header, footer, or data rows. Basically, you should only see that color if the table component is larger than the space needed to show the rows and columns of data. Change the sample app from "100" rows to "2" to see an example.

Unrelated to your question, I do see your chosen dead area color (red) on your screen shot, but it's below the THEAD and TFOOT. It should not be appearing there. Maybe there's a platform-specific issue with Firefox on Windows? I don't have Windows, but I tested Firefox's nightly build on Windows 7 using Browserling and I'm not seeing it there.
