### ISSUE TITLE
Lazy load large data sets in pages

### ISSUE THREAD

**Issue by druppy** [richardtallent/vue-scrolling-table#17]
I really like this table, and the layout is really nice moden and simple.

I like to be able to lazy load really large sets of data, but only when the user needs them.

Are there a way to do this ? 

I guess the idea could be to provide an interface for page load, and a total row count. If we then only load a page of lets say 25, we render these in the proper location inside the tbody container. This will make a scroll bar that makes sense to the user, and pageload only on needed data.

I would love to provide the logic, but the html/css part is hard to get right (need lots of w3c insight)

**Comment by richardtallent** [comment]
Hi @druppy,

This component is completely agnostic to paging of data. Whatever rows *you* render in the "tbody" slot is what it will show.

For my own applications, I have written another component (not open-source -- wrote it on my day job) that wraps this component and provides a paging interface (page numbers, next/last button, etc.). It emits events when the user navigates between pages, and my app then queries the API and returns the new set of rows to it to render. I'm sure you can do the same easily. For the paging interface, you could use write your own, or use existing paging components like the one in Veutify, or the CSS-only one in Bulma.

**Comment by richardtallent** [comment]
Oh, if you're referring to an "infinite" scroll (one where the scroll bar's height and position are controlled by additional logic rather than the actual height of the tbody, I think that would be outside the reasonable scope of this component.

**Comment by druppy** [comment]
Not exactly infinite scroll, more like https://dgrid.io
But i guess the point is, that you cant control tbody as much as needed, and dgrid is an old dojo project, and it really need a vue version :-)
