### ISSUE TITLE
There is problem with width of columns

### ISSUE THREAD

**Issue by Kariamba** [richardtallent/vue-scrolling-table#19]
I discarded "width", "max-width" and "min-width" styles from td elements and got broken table.
Column width of thead and tbody are differnt.

Here screenshot: http://prntscr.com/p02hi8

**Comment by noook** [comment]
Noticed aswell. And when inherting / seting manual values, there still is a difference of width between columns

**Comment by richardtallent** [comment]
Ah! I somehow missed this issue, sorry about that, @Kariamba.

You **do** need to set each column's CSS `width`, `min-width`, and `max-width`, both in the header and body, to the same values (in absolute units -- pixels, points, ems, etc., not %) to ensure that each data column lines up under its header. Removing that CSS will result in misalignment.

This is explained in greater detail in the readme, but basically, the only way to do the dual-scrolling with a frozen header is to override the `display` of the `thead`, `tbody`, and `tfoot`. But that means the browser no longer renders them as a table, which means there's no browser logic that says that, say, column 3 of the `thead` should be the same width as column 3 of row 46 of the `tbody`.

If you want your table to have an "automatic" width for certain columns, you'll need to implement an algorithm to compute a suitable width for each column. I don't have an algorithm for this handy, but it would involve parameters such as total length, whether wrapping is enabled, and the maximum non-whitespace character run within the values. Font metrics can be tricky, but using a `em` units and scaling back from there (say, to assume that 1 character = 0.8em) should be fine.

@noook, can you provide an online example of what you're seeing? There may still be situations where a browser might try to make a column wider to, for example, accommodate a very long header name, but I've not had any issues with this that I recall. (Specifying `overflow:hidden` on the cell may help if your text is too long for the manually-set width.)

**Comment by Kariamba** [comment]
@richardtallent thank you for reply. It takes me some time to return to UI and my table, but I'll try several experiments.
