### ISSUE TITLE
Enhancement: Vue-Scrolling-Table with Search Bar and Sorting

### ISSUE THREAD

**Issue by deanilvincent** [richardtallent/vue-scrolling-table#2]
Is there any feature like there's a search and sorting for this table? Thank you

**Comment by richardtallent** [comment]
Hi Mark,

This really isn't a standalone table component, it's more of a table wrapper or scaffold. It doesn't render any TR, TH, or TD elements, it just manages the THEAD, TBODY, and TFOOT. So there's not really anything this component could do around searching or sorting.

While it doesn't have full scrolling support, if you need a more complete table, I recommend looking into vue-tables-2, it does full table rendering and I believe it has sort and filter controls available.

https://github.com/matfish2/vue-tables-2
