### ISSUE TITLE
Could you add Virtual Scrolling for lazy loading

### ISSUE THREAD

**Issue by AllanOricil** [richardtallent/vue-scrolling-table#20]
I liked if. But it could be better if I could pass all columns and data rows for the component to mount to them dom only the cells that can be seen based on the position of the scrollbars. This would help to improve performance. Specially for horizontal scrolling. For vertical scrolling would be nice to have, as we can fix it by paginating the data.

**Comment by richardtallent** [comment]
Hi! This is a very simple component, intended for fairly small datasets that still require scrolling.

Virtual scrolling is nice, but it's well beyond the scope of this component's use case. I recommend finding a more robust table component that is designed around that feature.
