### ISSUE TITLE
Filtering columns?

### ISSUE THREAD

**Issue by dmikester1** [richardtallent/vue-scrolling-table#8]
How tough would it be to add live filtering of columns on this project?  So text boxes above specific columns and when you type it live updates the table.  Also would be nice for special filters like >= 3.2 for numeric columns, or select box for a few different values, etc.

**Comment by richardtallent** [comment]
Hi!

I've done exactly what you're talking about for an application I manage at my day job. It was really easy. Just put the filter form elements in the TH cells you create in your `thead` slot, bind them to data elements in your Vue application, and use a `computed` value of filtered rows when you loop through your `tbody` rendering. E.g.:

```
<script>
...
data: () => {
    filterColor: "",
    items: [... your rows]
},
computed: {
  filteredItems() {
    const self = this
    return this.items.filter(i => i.color==filterColor || !filterColor)
  } 
}
</script>
<vue-scrolling-table>
  <template slot="thead">
    <tr>
	  <th>Color
		<select v-model="filterColor"><option>...</select>
	  </th>
...
    </tr>
  </template>
  <template slot="tbody">
    <tr v-for="item in filteredItems" :key="item.id">
	  <td>{{ item.color }}</td>
...
    </tr>
  </template>
</vue-scrolling-table>
```

If you need the filters to trigger a remote API call, you'd need to use the @update or @input handlers to trigger the API call to refresh the items.

If you're getting stuck figuring out how to *dynamically* create columns with different types of components in them for different field types, see the docs here for how to create dynamic components:

https://vuejs.org/v2/guide/components-dynamic-async.html
