### ISSUE TITLE
trying to custumize table column width

### ISSUE THREAD

**Issue by piyushSinghalDemo** [richardtallent/vue-scrolling-table#9]
Hi ,
I want to give custom width for every column as per some bigger text, but by default it is taking some fixed width  "min-width: 10em;" is there any way i can solve it ?

**Comment by richardtallent** [comment]
Hi,

You would override the width using simple CSS. Use the same value for width, min-width, and max-width to get consistent results across browsers.

The example application shows an example of this, it defines a "w2" class that is 20em and is applied to two columns in the example grid. You can see it here and look at the source code to see how it works:

https://github.com/richardtallent/vue-scrolling-table-sample

**Comment by piyushSinghalDemo** [comment]
It worked,
Thanks
